### ISSUE TITLE
17track supplies invalid sensor names for HomeAssistant Markdown

### ISSUE THREAD

**Issue by DrToxic** [shaiu/pyseventeentrack#3]
**Describe the bug**
Markdown is unable to pull package information. Trying to make a markdown card for packages in transit to show more information.
Error shown: TemplateSyntaxError: expected token 'end of statement block', got 'track_in_transit'

**To Reproduce**
Have 17track setup.
track an active package.
create markdown card with the following code:
```
{% for package in states.sensor.17track_in_transit.attributes.packages %}

>- **{{ package.friendly_name }} ({{ package.tracking_number }}):** {{ package.info_text }}

{% endfor %}
```

**Expected behavior**
I expect to see a markdown card with package information.
Instead, I see an error with an invalid sensor name "track_in_transit", even though I have specified "17track_in_transit".

**Screenshots**
![image](https://github.com/user-attachments/assets/ea6b94f0-8f55-4d39-ae04-957035e3673c)

**Additional context**
This worked fine when using "seventeentrack_in_transit".
My presumption from testing, is that homeassistant can't handle sensors with numerical names. the "17" is completely ignored, even when using quotes around the sensor name.

More information has been found on this issue and can be seen here: https://community.home-assistant.io/t/entity-names-starting-with-digits/609468

I have solved my own issue using the link above, however I thought you should know as the problem reported is default behavior.
![image](https://github.com/user-attachments/assets/4846c49a-4bfd-4a73-9359-ec5dcd412d28)

**Comment by shaiu** [comment]
@DrToxic 
I did this and it works:

```
{% for package in states.sensor.seventeentrack_packages_in_transit.attributes.packages %}

>- **{{ package.friendly_name }} ({{ package.tracking_number }}):** {{ package.info_text }}

{% endfor %}
```

I think you're missing "_packages" inside the sensor name.
Anyway when you start writing "states.sensor." the editor will start to complete you and you should use that when building these kind of markdown.

Please let me know if that fixes the issue

**Comment by DrToxic** [comment]
That’s got it. Thank you 😊
